name: ic_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  go_router: ^14.6.3
  custom_navigation_bar: ^0.8.2
  another_flutter_splash_screen: ^1.2.1
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  swipe_refresh: ^1.1.2
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash.png
    - assets/images/icon.png

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas-Neue-Bold.otf
        - asset: assets/fonts/Bebas-Neue-Regular.otf

